DROP TABLE IF EXISTS PERSONS;
CREATE TABLE PERSONS(ID INT PRIMARY KEY,FIRST_NAME VARCHAR(255),LAST_NAME VARCHAR(255));
INSERT INTO PERSONS VALUES(1001,'Tom','Cat');
INSERT INTO PERSONS VALUES(1002,'Jerry','Mouse');
INSERT INTO PERSONS VALUES(1003,'Mickey','Mouse');
INSERT INTO PERSONS VALUES(1004,'Donald','Duck');